stages:
  creation_dataset:
    cmd: python scripts/create_dataset.py
    deps:
    - scripts/create_dataset.py
    outs:
    - assets/data
  creation_features:
    cmd: python scripts/extract_features.py
    deps:
    - assets/data
    - scripts/extract_features.py
    outs:
    - assets/features
